apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086/
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: my-bucket
      tlsSkipVerify: true
    secureJsonData:
      token: my-token
