version: "3.8"

services:
  mosquitto:
    container_name: MQTT_Broker
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1883:1883
      - 8883:8883
    networks:
      - localnet
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data

  node-red:
    container_name: Node-RED
    image: nodered/node-red:3.0.2
    depends_on:
      - mosquitto
    environment:
      - TZ=Europe/Berlin
    ports:
      - 1880:1880
    networks:
      - localnet
    volumes:
      - ./node-red:/data

  influxdb:
    container_name: Database
    image: influxdb:2.3.0
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin12345
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    ports:
      - 8086:8086
    networks:
      - localnet

  grafana:
    container_name: Grafana
    image: grafana/grafana-enterprise:10.0.2
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    networks:
      - localnet
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/

networks:
  localnet:
